import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { SystemEnvWriter } from '../../src/core/SystemEnvWriter.js';

describe('SystemEnvWriter', () => {
  let tempDir: string;
  let activeShPath: string;
  let writer: SystemEnvWriter;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'envize-test-'));
    activeShPath = path.join(tempDir, 'active.sh');
    writer = new SystemEnvWriter(activeShPath, 'bash');
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  describe('write', () => {
    it('should write environment variables to file', () => {
      writer.write({ KEY1: 'value1', KEY2: 'value2' });

      expect(fs.existsSync(activeShPath)).toBe(true);
      const content = fs.readFileSync(activeShPath, 'utf-8');
      expect(content).toContain("export KEY1='value1'");
      expect(content).toContain("export KEY2='value2'");
    });

    it('should include header comments', () => {
      writer.write({ KEY: 'value' });

      const content = fs.readFileSync(activeShPath, 'utf-8');
      expect(content).toContain('Generated by envize');
      expect(content).toContain('Updated:');
    });

    it('should escape single quotes', () => {
      writer.write({ KEY: "value'with'quotes" });

      const content = fs.readFileSync(activeShPath, 'utf-8');
      expect(content).toContain("'\\''");
    });
  });

  describe('clear', () => {
    it('should delete the global file', () => {
      fs.writeFileSync(activeShPath, 'some content');
      expect(fs.existsSync(activeShPath)).toBe(true);

      writer.clear();

      expect(fs.existsSync(activeShPath)).toBe(false);
    });

    it('should not throw if file does not exist', () => {
      expect(() => writer.clear()).not.toThrow();
    });
  });

  describe('exists', () => {
    it('should return true when file exists', () => {
      fs.writeFileSync(activeShPath, 'content');
      expect(writer.exists()).toBe(true);
    });

    it('should return false when file does not exist', () => {
      expect(writer.exists()).toBe(false);
    });
  });

  describe('read', () => {
    it('should return empty object when file does not exist', () => {
      expect(writer.read()).toEqual({});
    });

    it('should parse export statements', () => {
      const content = `# comment
export KEY1='value1'
export KEY2='value2'
`;
      fs.writeFileSync(activeShPath, content);

      const variables = writer.read();
      expect(variables.KEY1).toBe('value1');
      expect(variables.KEY2).toBe('value2');
    });
  });

  describe('update', () => {
    it('should add and remove variables', () => {
      writer.write({ OLD: 'old', KEEP: 'keep' });

      writer.update({ NEW: 'new' }, ['OLD']);

      const content = fs.readFileSync(activeShPath, 'utf-8');
      expect(content).toContain("export KEEP='keep'");
      expect(content).toContain("export NEW='new'");
      expect(content).not.toContain('OLD');
    });

    it('should clear file when no variables remain', () => {
      writer.write({ KEY: 'value' });

      writer.update({}, ['KEY']);

      expect(fs.existsSync(activeShPath)).toBe(false);
    });
  });

  describe('getPath', () => {
    it('should return the active.sh path', () => {
      expect(writer.getPath()).toBe(activeShPath);
    });
  });
});
